# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='instaclone.Profile'),
        ),
    ]
